### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by arokem** [Brainhack-Proceedings-2015/Pfan_HBM_SOBF#3]
The manuscript contains a link to https://github.com/SOBF, which doesn't exist.

**Comment by arokem** [comment]
I assume the code to implement these simulations are in this repository?

**Comment by pfannmoe** [comment]
Hi, the link is now pointing to our project on the hackathon web page. Yours pfannmoe

**Comment by pfannmoe** [comment]
I have added the matlab code!

**Comment by arokem** [comment]
:+1:
