### ISSUE TITLE
The 'jet' color map

### ISSUE THREAD

**Issue by arokem** [Brainhack-Proceedings-2015/Pfan_HBM_SOBF#4]
Is not appropriate for use with the human visual system: https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/

Please consider recreating these figures with a more appropriate color-map. For these data a bipolar color-map would be a good choice. For example Matplotlib's RdBu, or this one for Matlab: http://www.mathworks.com/matlabcentral/fileexchange/25536-red-blue-colormap

**Comment by pfannmoe** [comment]
The colormap is now adapted.

**Comment by arokem** [comment]
Looks much better!
