### ISSUE TITLE
I can't comment on #5

### ISSUE THREAD

**Issue by arokem** [Brainhack-Proceedings-2015/Pfan_HBM_SOBF#7]
Because you locked it...

**Comment by pfannmoe** [comment]
I was told to do so. Sorry for that. What was your comment about?

**Comment by arokem** [comment]
"This was better:
https://github.com/Brainhack-Proceedings-2015/Pfan_HBM_SOBF/commit/e242c05ddf9c6bb179049af098735290daf764e3

You are the authors of this, and you should hold the copyright."

**Comment by pfannmoe** [comment]
I am also a bit surprised, but I was advised to change it to MIT license.

**Comment by arokem** [comment]
I don't have a problem with the kind of license, but I suggest that the authors hold the copyright, instead of "brainhack proceedings"

**Comment by ccraddock** [comment]
I am sorry for the confusion. I thought you were asking me if I would like to hold the copyright to the template. I would not, and would rather the template be copyrighted with the MIT license. As far as the authors contributions I agree that they should hold the copyright.

**Comment by arokem** [comment]
All of that should be encoded in the license:

"the following files are (c) brainhack, 2015:

The text and code in the following files are (c) author1, author2, ... 2015:

The license for all components is as follows:

<put in the MIT license here>

"

Or something like that.

On Wed, Apr 20, 2016 at 10:38 AM, Cameron Craddock <notifications@github.com

**Comment by pfannmoe** [comment]
I hope this version of the license file is appropriate for everybody!

**Comment by arokem** [comment]
LGTM!
